
stages:
  - test
  - release

before_script:
  - python3 -m pip install .

test:
  image: python:latest
  stage: test
  script:
    - pip install pytest
    - pytest test/ --ignore=test/instruments/chandra/

pages:
  image: python:latest
  stage: release
  script:
    - pip install "sphinx<8.2" sphinxcontrib-bibtex pydata-sphinx-theme myst-parser
    - sh docs/generate.sh
    - mv docs/build/ public/
  artifacts:
    paths:
    - public
  only:
  - main
