image: python:latest

stages:
  - test

before_script:
  # - python3 -m pip install numpy ducc0 jax jaxlib astropy
  - python3 -m pip install .
  - pip install -U pytest

test:
  stage: test
  script:
    - pytest test/library/test_build_exposure_function.py
    - pytest test/library/test_build_exposure_readout_function.py
    - pytest test/library/test_diagnostics.py
    - pytest test/library/test_minimization_parser.py
    - pytest test/library/test_mock_data.py
    - pytest test/library/test_sky_model.py
    # - pytest test/library/test_slice_patches.py
    # - pytest test/library/instruments/chandra/test_chandra_observation.py
