image: python:latest

stages:
  - test

before_script:
  - python3 -m pip install --user numpy ducc0 jax jaxlib astropy
  - python3 -m pip install --user --break-system-packages .

test:
  stage: test
  script:
    - pytest-3 test/library/test_build_exposure_function.py
