
stages:
  - test
  - release

before_script:
  - python3 -m pip install -e .

test:
  image: python:latest
  stage: test
  script:
    - pip install pytest pytest-cov
    - pytest --cov=jubik0 test/
  coverage: '/TOTAL\s+\d+\s+\d+\s+(\d+%)$/'

pages:
  image: python:latest
  stage: release
  script:
    - pip install .[doc]
    - sh docs/generate.sh
    - mv docs/build/ public/
  artifacts:
    paths:
    - public
  only:
  - main
