datasets:
- df_14423_observation.npy
- df_9107_observation.npy
- df_13738_observation.npy
- df_13737_observation.npy
- df_13739_observation.npy
- df_13740_observation.npy
- df_13741_observation.npy
- df_13742_observation.npy
- df_13743_observation.npy
- df_14424_observation.npy
- df_14435_observation.npy
grid:
  npix_s : 1024
  npix_e : 2
  elim : [2.0, 10.0]
  fov : 21.0

psf_sim:
  num_rays: 1.0E+6

priors_diffuse:
  offset_mean: 0
  offset_std: [1, 0.5]
  fluctuations: [1, 1]
  loglogavgslope: [-3.0, 1.5]
  flexibility: [2.0, 2.0]
  asperity: [0.1, 0.5]
  prefix: diffuse

points:
  alpha: 3
  q: 0.7

ic_newton:
  name: Newton
  deltaE: 0.5
  iteration_limit: 5
  convergence_level: 5

ic_sampling:
  name: Sampling(lin)
  deltaE: 0.05
  iteration_limit: 100

global_it: 30
Nsamples: 4


outroot : "" 
prefix : df
