Nsamples: 4
datasets:
- 14423
- 9107
- 13738
- 13737
- 13739
- 13740
- 13741
- 13742
- 13743
- 14424
- 14435
grid:
  elim:
  - 2.0
  - 10.0
  fov: 21.0
  npix_e: 2
  npix_s: 4096
ic_newton:
  convergence_level: 5
  deltaE: 0.5
  iteration_limit: 1
  convergence_level: 5

ic_sampling:
  deltaE: 0.05
  iteration_limit: 10

global_it: 30
Nsamples: 4


outroot : "" 
prefix : df
