priors_diffuse:
  offset_mean: 0
  offset_std: [1, 0.5]
  fluctuations: [1, 1]
  loglogavgslope: [-3.0, 1.5]
  flexibility: [2.0, 2.0]
  asperity: [0.1, 0.5]
  prefix: diffuse

points:
  alpha: 3
  q: 0.7

ic_newton:
  name: Newton
  deltaE: 0.5
  iteration_limit: 5
  convergence_level: 5

ic_sampling:
  name: Sampling(lin)
  deltaE: 0.05
  iteration_limit: 100

global_it: 30

datasets:
  - df_14423_observation.npy 
  - df_9107_observation.npy 
  - df_13738_observation.npy 
  - df_13737_observation.npy 
  - df_13739_observation.npy 
  - df_13740_observation.npy 
  - df_13741_observation.npy 
  - df_13742_observation.npy 
  - df_13743_observation.npy 
  - df_14424_observation.npy 
  - df_14435_observation.npy 

