obs_info:
  obs14410: # Comacluster #FIXME:Are all files for mock needed?
    obsID: 14410
    data_location: ../data/14410/
    event_file: primary/acisf14410N002_evt2.fits
    aspect_sol: primary/pcadf14410_000N001_asol1.fits
    bpix_file: primary/acisf14410_000N002_bpix1.fits
    mask_file: secondary/acisf14410_000N002_msk1.fits
    instrument: ACIS-I

grid:
  npix_s: 512
  npix_e: 3
  fov: 2040

files:
  data_outroot: ''

psf:
  num_rays: 10000
  npatch: 8
  margfrac: 0.062