seed: 86
# threads: 8
mock: False
# mock_psf: False
load_mock_data: False
telescope:
  tm_ids : [1] #,2,3,4,6]
  fov: 3600 # in arcsec
  pattern: 15
  detmap: True
  exp_cut: 500

point_source_defaults:
  alpha: 1.
  q: 1e6

psf:
 method: 'LINJAX'
 energy: '3000'
  # LIN config
 npatch: 8
 margfrac: 0.062
 want_cut: False

  # MSC config
#  base: [3,3]
#  min_baseshape: [8,8]
#  linlevel: [100,100]
#  kernel_sizes: [[3,3],]
#  keep_overlap: [[True,True],]
#  local_kernel: [True,True]

  # config for homogeneous gauss psf
#  gauss_var: 5

 plotting:
  enabled: True
  slice: Null
  dpi: 800

grid:
  npix: 512
  padding_ratio: 1.203
  energy_bin:
    e_min: 2.0
    e_max: 4.5


files:
  obs_path: '../data/LMC_SN1987A/'
  input: 'pm00_700161_020_EventList_c001.fits'
  output: 'small_processed_pm00_700161_020_data.fits'
  exposure: 'small_expmap_pm00_700161_020.fits'
  psf_path : '../data/psf_info/'
  psf_base_filename: '2dpsf_190219v05.fits'
  res_dir: 'results/Default_run'

priors:
  point_sources:
    alpha: 1.
    q: 1.E-6
  diffuse:
    offset:
      offset_mean: -10. # exposure norm = 4.4 *10^-5
      offset_std:
        - 0.2
        - 0.05
    fluctuations:
      fluctuations:
        - 1.5
        - 0.8
      loglogavgslope:
        - -3.
        - 1.0
      flexibility:
        - 0.8
        - 0.1
      asperity:
        - 0.2
        - 0.1
    prefix: diffuse_

minimization:
  resume: False
  n_total_iterations: 15
  n_samples: 4
  draw_linear_kwargs:
    cg_name : lin sampling
    cg_kwargs:
      absdelta: 1.e-4
      maxiter: 60
  nonlinearly_update_kwargs:
    minimize_kwargs:
      name: nonlin sampling
      xtol: 2.e-4
      cg_kwargs:
        name: null
      maxiter: 25
  kl_kwargs:
    minimize_kwargs:
      name: "M"
      absdelta: 1.e-6
      maxiter: 15
      cg_kwargs:
        name: "MCG"
  sample_mode: nonlinear_sample