seed: 86
esass_image: DR1
telescope:
  tm_ids : [1, 2, 3, 4, 6]
  fov: 4327 # in arcsec
  pattern: 15
  detmap: True
  exp_cut: 500
  badpix_correction: True

psf:
 method: 'LINJAX'
 energy: ['0277', '1486', '3000'] #FIXME: check whether to use '0930'
  # LIN config
 npatch: 8
 margfrac: 0.062
 want_cut: False

  # MSC config
#  base: [3,3]
#  min_baseshape: [8,8]
#  linlevel: [100,100]
#  kernel_sizes: [[3,3],]
#  keep_overlap: [[True,True],]
#  local_kernel: [True,True]

  # config for homogeneous gauss psf
#  gauss_var: 5

plotting:
  enabled: True
  slice: Null
  dpi: 800

grid:
  sdim: 512
  edim: 3 # FIXME: remove this parameter
  s_padding_ratio: 1.203
  e_padding_ratio: 1.
  energy_bin:
    e_min:
    - 0.2
    - 1.0
    - 2.0
    e_max:
    - 1.0
    - 2.0
    - 4.5
    e_ref:
    - 2


files:
  obs_path: '../data/LMC_SN1987A/'
  data_dict: 'data.pkl'
  processed_obs_folder: 'processed'  # only needed for actual data
  input: 'pm00_700161_020_EventList_c001.fits'
  output: 'pm00_700161_020_data.fits'
  exposure: 'pm00_700161_020_expmap.fits'
  psf_path : '../data/psf_info/'
  psf_base_filename: '2dpsf_190219v05.fits'
  res_dir: 'results/Default_run_mf'
# If mock:
  mock_gen_config: 'mock_config.yaml' # Only set for mock
  pos_dict: 'pos.pkl' # only needed for mock

priors:
  point_sources:
    spatial:
      alpha: 1.0001
      q: 5.E-7
      key: points
    plaw:
      offset:
        offset_mean: -2.0
        offset_std:
          - 0.3
          - 0.05
      fluctuations:
        fluctuations:
          - 0.5
          - 0.05
        loglogavgslope:
          - -1.
          - 0.0002
        flexibility:
          - 0.3
          - 0.1
        asperity:
          Null
        # harmonic_type: "Fourier"
        non_parametric_kind: "power"
      prefix: points_plaw_
    dev_wp:
      x0:
        - 0
        - 0.01
      sigma:
        - 0.01
        - 0.02
      name: 'points_dev_wp'
#    dev_corr:
#      fluctuations:
#        fluctuations:
#          - 1.0
#          - 5.0e-3
#        loglogavgslope:
#          - -3
#          - 1.0e-2
#        flexibility:
#          - 2.0
#          - 5.0e-1
#        asperity:
#        non_parametric_kind: "power"
#        # harmonic_type: "Fourier"
#      prefix: points_dev
#      offset:
#        offset_mean: 0.0
#        offset_std:
#          - 1.0e-3
#          - 1.0e-4
  diffuse:
    spatial:
      offset:
        offset_mean: -11.
        offset_std:
          - 0.5
          - 0.1
      fluctuations:
        fluctuations:
          - 0.5
          - 0.2
        loglogavgslope:
          - -4.0
          - 0.3
        flexibility:
          - 0.4
          - 0.1
        asperity:
          Null
        non_parametric_kind: "power"
        # harmonic_type: "Fourier"
      prefix: diffuse_spatial_
    plaw:
      offset:
        offset_mean: -2.0
        offset_std:
          - 0.3
          - 0.05
      fluctuations:
        fluctuations:
          - 0.5
          - 0.05
        loglogavgslope:
          - -5.
          - 1.0e-2
        flexibility:
          - 0.5
          - 0.05
        asperity:
          Null
        non_parametric_kind: "power"
        # harmonic_type: "Fourier"
      prefix: diffuse_plaw_
    # dev_wp:
    #   x0:
    #     - 0
    #     - 0.1
    #   sigma:
    #     - 0.3
    #     - 0.1
    #   dt: 1
    #   name: 'diffuse_dev_wp'
#    dev_corr:
#      fluctuations:
#        fluctuations:
#          - 1.0
#          - 5.0e-3
#        loglogavgslope:
#          - -3
#          - 1.0e-2
#        flexibility:
#          - 2.0
#          - 5.0e-1
#        asperity:
#        non_parametric_kind: "power"
#        # harmonic_type: "Fourier"
#      prefix: diffuse_dev_
#      offset:
#        offset_mean: 0.0
#        offset_std:
#          - 1.0e-3
#          - 1.0e-4

minimization:
  resume: False
  n_total_iterations: 15
  n_samples: 4
  draw_linear_kwargs:
    cg_name : lin sampling
    cg_kwargs:
      absdelta: 1.e-4
      maxiter: 60
  nonlinearly_update_kwargs:
    minimize_kwargs:
      name: nonlin sampling
      xtol: 2.e-4
      cg_kwargs:
        name: null
      maxiter: 25
  kl_kwargs:
    minimize_kwargs:
      name: "M"
      absdelta: 1.e-6
      maxiter: 10
      cg_kwargs:
        name: "MCG"
  sample_mode: nonlinear_resample
