seed: 89
telescope:
  tm_id : 1
  rebin: 80
  pattern: 15
plotting:
  enabled: True
  slice:
    - 1100
    - 2000
    - 800
    - 2000
  dpi: 800
files:
  obs_path: 'data/'
  input: 'fm00_700203_020_EventList_c001.fits'
  output: 'processed_LMC_SN1987A_data.fits'
  exposure: 'expmap_LMC_SN1987A.fits'
grid:
  npix: 1024
  padding_ratio: 2.
  distances: 0.1 # FIXME
  energy_bin:
    e_min: 2.0
    e_max:  4.5

priors:
  point_sources:
    alpha: 5.5
    q: 0.3
  diffuse:
    offset:
      offset_mean: 0.
      offset_std:
        - .5
        - 0.1
    fluctuations:
      flexibility:
      - 3.0
      - 2.0
      fluctuations:
      - 1.
      - .5
      loglogavgslope:
      - -4.0
      - 1.5
      asperity: Null
    prefix: diffuse_

minimization:
  geovi: True
  total_iterations: 15
  n_samples: 'lambda i_iter: 6 if i_iter < 13 else 10'
  ic_newton:
    convergence_level: 2
    deltaE: 0.1
    iteration_limit: 7
    name: Newton
  ic_sampling:
    deltaE: 0.02
    iteration_limit: 5
    name: Sampling(lin)
  ic_sampling_nl:
    deltaE: 0.05
    iteration_limit: 3
    name: Sampling(nonlin)

#minimization:
#  geovi: False
#  total_iterations: 1
#  n_samples: 'lambda i_iter: 1 if i_iter < 13 else 10'
#  ic_newton:
#    convergence_level: 1
#    deltaE: 0.5
#    iteration_limit: 1
#    name: Newton
#  ic_sampling:
#    deltaE: 0.5
#    iteration_limit: 1
#    name: Sampling(lin)
#  ic_sampling_nl:
#    deltaE: 0.05
#    iteration_limit: 3
#    name: Sampling(nonlin)

