seed: 42
mock: True
mock_psf: True
load_mock_data: False

telescope:
  tm_id : 1
  fov: 3600 # in arcsec
  pattern: 15

psf:
  method: 'invariant'
  energy: '3000'

  # LIN config
  npatch: 8
  margfrac: 0.2
  want_cut: False

  # MSC config
  b: [3,3]
  q: [4,4]
  c: [2,2]
  min_m0: [10,10]
  linear: False

  # config for homogeneous gauss psf
  gauss_var: 5

plotting:
  enabled: True
  slice: Null
  dpi: 800

files:
  obs_path: '../data/LMC_SN1987A/'
  input: 'pm00_700161_020_EventList_c001.fits'
  output: 'small_processed_pm00_700161_020_data.fits'
  exposure: 'small_expmap_pm00_700161_020.fits'
  psf_path : '../data/tm1/bcf/tm1_2dpsf_190219v05.fits'
  res_dir: 'results/LMC_first_reconstruction'

grid:
  npix: 426
  padding_ratio: 1.203
  energy_bin:
    e_min: 2.0
    e_max: 4.5

priors:
  point_sources:
    alpha: 1.
    q: 1e-6
  diffuse:
    offset:
      offset_mean: -10.
      offset_std:
        - 0.2
        - 0.05
    fluctuations:
      fluctuations:
        - 1.5
        - 0.8
      loglogavgslope:
        - -4.
        - 1.5
      flexibility:
        - 1.2
        - 0.5
      asperity: Null
    prefix: diffuse_

minimization:
  resume: False
  geovi: True
  transition: True
  total_iterations: 20
  n_samples: 4 #'lambda i_iter: 6 if i_iter < 13 else 10'
  ic_newton:
    convergence_level: 2
    deltaE: 0.1
    iteration_limit: 10
    name: Newton
  ic_sampling:
    deltaE: 0.02
    iteration_limit: 30
    name: Sampling(lin)
  ic_sampling_nl:
    deltaE: 0.1
    iteration_limit: 8
    name: Sampling(nonlin)
  ic_transition:
    deltaE: 1e-4
    iteration_limit: 50
    name: Transition
    start: 1