seed: 89
grid:
  npix: 1024
  padding_ratio: 2.
  distances: 0.1 # FIXME

priors:
  point_sources:
    alpha: 5.5
    q: 0.3
  diffuse:
    offset:
      offset_mean: 0.
      offset_std:
        - .5
        - 0.1
    fluctuations:
      flexibility:
      - 3.0
      - 2.0
      fluctuations:
      - 1.
      - .5
      loglogavgslope:
      - -4.0
      - 1.5
      asperity: Null
    prefix: diffuse_

minimization:
  geovi: True
  total_iterations: 15
  n_samples: 'lambda i_iter: 6 if i_iter < 13 else 10'
  ic_newton:
    convergence_level: 2
    deltaE: 0.1
    iteration_limit: 7
    name: Newton
  ic_sampling:
    deltaE: 0.02
    iteration_limit: 5
    name: Sampling(lin)
  ic_sampling_nl:
    deltaE: 0.05
    iteration_limit: 3
    name: Sampling(nonlin)

#minimization:
#  geovi: False
#  total_iterations: 1
#  n_samples: 'lambda i_iter: 1 if i_iter < 13 else 10'
#  ic_newton:
#    convergence_level: 1
#    deltaE: 0.5
#    iteration_limit: 1
#    name: Newton
#  ic_sampling:
#    deltaE: 0.5
#    iteration_limit: 1
#    name: Sampling(lin)
#  ic_sampling_nl:
#    deltaE: 0.05
#    iteration_limit: 3
#    name: Sampling(nonlin)

