seed: 86
# threads: 8
mock: False
# mock_psf: False
load_mock_data: False
esass_image: DR1
telescope:
  tm_ids : [1, 2]
  fov: 4327 # in arcsec
  pattern: 15
  detmap: True
  exp_cut: 500
  badpix_correction: True

point_source_defaults:
  alpha: 1.
  q: 1e6

psf:
 method: 'LINJAX'
 energy: ['1486', '3000']
  # LIN config
 npatch: 8
 margfrac: 0.062
 want_cut: False

  # MSC config
#  base: [3,3]
#  min_baseshape: [8,8]
#  linlevel: [100,100]
#  kernel_sizes: [[3,3],]
#  keep_overlap: [[True,True],]
#  local_kernel: [True,True]

  # config for homogeneous gauss psf
#  gauss_var: 5

plotting:
  enabled: True
  slice: Null
  dpi: 800

grid:
  sdim: 512
  edim: 2 # FIXME: remove this parameter
  s_padding_ratio: 1.203
  e_padding_ratio: 2.
  energy_bin:
    e_min:
    - 1.0
    - 2.0
    e_max:
    - 2.0
    - 4.5


files:
  obs_path: '../data/LMC_SN1987A/'
  input: 'pm00_700161_020_EventList_c001.fits'
  output: 'small_processed_pm00_700161_020_data.fits'
  exposure: 'small_expmap_pm00_700161_020.fits'
  psf_path : '../data/psf_info/'
  psf_base_filename: '2dpsf_190219v05.fits'
  res_dir: 'results/Default_run'

priors:
  # point_sources:
  #   spatial:
  #     alpha: 1.
  #     q: 1.E-10 # VIEL ZU HOCH
  #     key: points
  #   plaw:
  #     fluctuations:
  #       fluctuations:
  #         - 0.5
  #         - 0.05
  #       loglogavgslope:
  #         - -6.
  #         - 0.0002
  #       flexibility:
  #         - 0.3
  #         - 0.1
  #       asperity:
  #         Null
  #       # harmonic_type: "Fourier"
  #       non_parametric_kind: "power"
  #     prefix: points_plaw
  #     offset:
  #       offset_mean: -2.0
  #       offset_std:
  #         - 0.3
  #         - 0.1
  #   dev_wp:
  #     x0:
  #       - 0
  #       - 0.00001
  #     sigma:
  #       - 0.00001
  #       - 0.00002
  #     dt: 1
  #     name: 'points_dev_wp'
#    dev_corr:
#      fluctuations:
#        fluctuations:
#          - 1.0
#          - 5.0e-3
#        loglogavgslope:
#          - -3
#          - 1.0e-2
#        flexibility:
#          - 2.0
#          - 5.0e-1
#        asperity:
#        non_parametric_kind: "power"
#        # harmonic_type: "Fourier"
#      prefix: points_dev
#      offset:
#        offset_mean: 0.0
#        offset_std:
#          - 1.0e-3
#          - 1.0e-4
  diffuse:
    spatial:
      offset:
        offset_mean: -12. #
        offset_std:
          - 0.5
          - 0.3
      fluctuations:
        fluctuations:
          - 1.5
          - 0.8
        loglogavgslope:
          - -3.5
          - 0.5
        flexibility:
          - 0.8
          - 0.1
        asperity:
          Null
        non_parametric_kind: "power"
        # harmonic_type: "Fourier"
      prefix: diffuse_spatial
    plaw:
      fluctuations:
        fluctuations:
          - 0.5
          - 0.05
        loglogavgslope:
          - -5.
          - 1.0e-2
        flexibility:
          - 0.5
          - 0.05
        asperity:
          Null
        non_parametric_kind: "power"
        # harmonic_type: "Fourier"
      prefix: diffuse_plaw
      offset:
        offset_mean: -2.0
        offset_std:
          - 0.3
          - 0.1
    # dev_wp:
    #   x0:
    #     - 0
    #     - 0.1
    #   sigma:
    #     - 0.3
    #     - 0.1
    #   dt: 1
    #   name: 'diffuse_dev_wp'
#    dev_corr:
#      fluctuations:
#        fluctuations:
#          - 1.0
#          - 5.0e-3
#        loglogavgslope:
#          - -3
#          - 1.0e-2
#        flexibility:
#          - 2.0
#          - 5.0e-1
#        asperity:
#        non_parametric_kind: "power"
#        # harmonic_type: "Fourier"
#      prefix: diffuse_dev
#      offset:
#        offset_mean: 0.0
#        offset_std:
#          - 1.0e-3
#          - 1.0e-4

minimization:
  resume: False
  n_total_iterations: 15
  n_samples: 4
  draw_linear_kwargs:
    cg_name : lin sampling
    cg_kwargs:
      absdelta: 1.e-4
      maxiter: 60
  nonlinearly_update_kwargs:
    minimize_kwargs:
      name: nonlin sampling
      xtol: 2.e-4
      cg_kwargs:
        name: null
      maxiter: 25
  kl_kwargs:
    minimize_kwargs:
      name: "M"
      absdelta: 1.e-6
      maxiter: 15
      cg_kwargs:
        name: "MCG"
  sample_mode: nonlinear_sample
